variable "aws_prefix" {}
variable "aws_region" {}
variable "aws_access_key" {}
variable "aws_secret_key" {}
variable "aws_vpc" {}
variable "aws_subnet_a" {}
variable "aws_subnet_b" {}
variable "aws_subnet_c" {}
variable "aws_ami" {}
variable "aws_subnet_id" {}
variable "aws_security_group_id" {}
variable "aws_pem_key_name" {}
